packages:
    - name: init
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: user
          binary: false
          main: ""
          runtime: python:default
          web: true
          webSecure: false
          environment: 
            NEO4J_PASSWORD: ""
